{{- if .Values.prepareCSI.enabled -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prepare-csi
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prepare-csi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prepare-csi
subjects:
- kind: ServiceAccount
  name: prepare-csi
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prepare-csi
  namespace: {{ .Release.Namespace }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: prepare-csi
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: prepare-csi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prepare-csi
  template:
    metadata:
      name: prepare-csi
      labels:
        app.kubernetes.io/name: prepare-csi
    spec:
      hostNetwork: true
      hostPID: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: iomesh.com/iscsi-installed
                operator: DoesNotExist
      serviceAccountName: prepare-csi
      containers:
      - name: prepare-csi
        image: {{ include "prepareCSI.image" . }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - mountPath: /host
          mountPropagation: HostToContainer
          name: host-root
      volumes:
      - hostPath:
          path: /
          type: Directory
        name: host-root
{{- end }}
