{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  database.yml.erb: |
    production:
      adapter: postgresql
      encoding: unicode
      database: {{ template "gitlab.psql.database" . }}
      username: {{ template "gitlab.psql.username" . }}
      password: "<%= File.read("/etc/gitlab/postgres/psql-password").strip.dump[1..-2] %>"
      host: {{ include "gitlab.psql.host" . | quote }}
      port: {{ template "gitlab.psql.port" . }}
      pool: {{ template "gitlab.psql.pool" . }}
      prepared_statements: {{ template "gitlab.psql.preparedStatements" . }}
      # load_balancing:
      #   hosts:
      #     - host1.example.com
      #     - host2.example.com
{{- include "gitlab.psql.ssl.config" . | indent 6 }}
  {{- if include "gitlab.geo.secondary" $ }}
  database_geo.yml.erb: |
    {{- include "gitlab.geo.database.yml" $ | nindent 4 }}
  {{- end }}
  {{- include "gitlab.rails.redis.resque" . | nindent 2 }}
  {{- include "gitlab.rails.redis.cache" . | nindent 2 }}
  {{- include "gitlab.rails.redis.sharedState" . | nindent 2 }}
  {{- include "gitlab.rails.redis.queues" . | nindent 2 }}
  {{- include "gitlab.rails.redis.cable" . | nindent 2 }}
  gitlab.yml.erb: |
    production: &base
      gitlab:
        host: {{ template "gitlab.gitlab.hostname" . }}
      {{- include "gitlab.appConfig.gitaly" . | nindent 6 }}
      {{- include "gitlab.appConfig.repositories" . | nindent 6 }}
      {{- include "gitlab.geo.config" $ | nindent 6 }}
  configure: |
    {{- include "gitlab.scripts.configure.secrets" (dict "required" "postgres rails-secrets migrations gitaly") | nindent 4 -}}
    {{- include "gitlab.psql.ssl.initScript" . | nindent 4 }}
    {{- include "gitlab.geo.psql.ssl.initScript" . | nindent 4 }}
{{- if .Values.global.operator.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-migrations-jobspec
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  template: |-
    {{- include (print $.Template.BasePath "/_jobspec.yaml") . | nindent 4 }}
{{- end }}
# Leave this here - This line denotes end of block to the parser.
{{- end }}
