{{- if and .Values.enabled (not .Values.global.operator.enabled) }}
{{ include (print $.Template.BasePath "/_serviceaccountspec.yaml") . }}
---
{{ include (print $.Template.BasePath "/_jobspec.yaml") . }}
{{- end }}
