{{- if .Values.global.config.storageclass.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-csi
{{- if .Values.global.config.storageclass.default }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}

provisioner: csi.vsphere.vmware.com
{{- if .Values.global.config.storageclass.storagepolicyname }}
parameters:
  storagepolicyname: {{ .Values.global.config.storageclass.storagepolicyname }}
{{- end -}}
{{- if .Values.global.config.storageclass.expansion }}
allowVolumeExpansion: true
{{- end -}}
{{- if .Values.global.config.labels }}
volumeBindingMode: WaitForFirstConsumer
{{- end -}}
{{- end -}}
