{{- if .Values.sparkOperator.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sparkOperator.name }}-spark-operator
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-delete-policy": hook-failed, before-hook-creation
    "helm.sh/hook-weight": "-10"
  labels:
    app.kubernetes.io/name: spark-operator
{{- end }}
