{{- if .Values.sparkOperator.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.sparkOperator.name }}-spark
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: spark-operator
{{- end }}
