{{- if .Values.theiaManager.enable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: theia-cli
  labels:
    app: theia-cli
rules:
  - apiGroups:
      - intelligence.theia.antrea.io
    resources:
      - networkpolicyrecommendations
    verbs:
      - get
      - list
      - create
      - delete
{{- end }}
