{{- if .Values.theiaManager.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: theia-cli-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: theia-cli
type: kubernetes.io/service-account-token
{{- end }}
