# Default values for sidekiq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/gitlab-org/charts/components/gitlab-operator
  pullSecrets: []
  # pullPolicy: IfNotPresent
  # tag: latest

# Which version of the operator to deploy
version: 0.9

init:
  resources:
    requests:
      cpu: 50m

## Support for tolerations for pod scheduling
tolerations: []

resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 100m
    memory: 64M

# A prefix for group name of GitLab CRD. It can be used for distinguishing
# different CRDs in a cluster, e.g. for development purposes such GitLab CI.
#crdPrefix:
