apiVersion: v1
appVersion: 2.190.1
description: The leading open source automation server
home: https://jenkins.io/
icon: https://wiki.jenkins-ci.org/download/attachments/2916393/logo.png
keywords:
- ci
- continuous integration
- continuous delivery
- continuous deployment
- devops
- automation
maintainers:
- email: unguiculus@gmail.com
  name: unguiculus
name: jenkins
sources:
- https://github.com/codecentric/helm-charts
- https://github.com/jenkinsci/jenkins
- https://github.com/jenkinsci/docker
- https://github.com/jenkinsci/docker-jnlp-slave
version: 1.5.1
