kind: ServiceAccount
apiVersion: v1
metadata:
  name: vsphere-csi-controller
  namespace: {{ .Release.Namespace }}
{{ include "vsphere.labels" . | indent 2 }}
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: vsphere-csi-node
  namespace: {{ .Release.Namespace }}
{{ include "vsphere.labels" . | indent 2 }}  
