apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsphere-default
  annotations:
    kubernetes.io/description: vSphere Storage class
{{- if .Values.storageclass.isDefault }}
    storageclass.kubernetes.io/is-default-class: "true"
{{- end }}
provisioner: csi.vsphere.vmware.com
allowVolumeExpansion: {{ .Values.storageclass.allowVolumeExpansion }}
volumeBindingMode: {{ .Values.storageclass.volumeBindingMode | quote }}
reclaimPolicy: {{ .Values.storageclass.reclaimPolicy | quote }}
{{- if .Values.storageclass.parameters }}
parameters:
{{ toYaml .Values.storageclass.parameters | indent 2 }}
{{- end }}
