apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networkpolicyrecommendations.crd.theia.antrea.io
  labels:
    app: theia
spec:
  group: crd.theia.antrea.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - jobType
                - policyType
                - executorInstances
                - driverCoreRequest
                - driverMemory
                - executorCoreRequest
                - executorMemory
              properties:
                jobType:
                  type: string
                limit:
                  type: integer
                policyType:
                  type: string
                startInterval:
                  type: string
                  format: datetime
                endInterval:
                  type: string
                  format: datetime
                nsAllowList:
                  type: array
                  items:
                    type: string
                excludeLabels:
                  type: boolean
                toServices:
                  type: boolean
                executorInstances:
                  type: integer
                driverCoreRequest:
                  type: string
                driverMemory:
                  type: string
                executorCoreRequest:
                  type: string
                executorMemory:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
                sparkApplication:
                  type: string
                completedStages:
                  type: integer
                totalStages:
                  type: integer
                startTime:
                  type: string
                  format: datetime
                endTime:
                  type: string
                  format: datetime
                errorMsg:
                  type: string
                recommendedNetworkPolicy:
                  type: object
                  properties:
                    spec: 
                      type: object
                      properties:
                        id:
                          type: string
                        resultType:
                          type: string
                        timeCreated:
                          type: string
                          format: datetime
                        yamls:
                          type: string
      additionalPrinterColumns:
        - description: Current state of the job
          jsonPath: .status.state
          name: State
          type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: networkpolicyrecommendations
    singular: networkpolicyrecommendation
    kind: NetworkPolicyRecommendation
    shortNames:
      - npr
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: recommendednetworkpolicies.crd.theia.antrea.io
  labels:
    app: theia
spec:
  group: crd.theia.antrea.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              type: object
              required:
                - id
                - timeCreated
                - resultType
                - yamls
              properties:
                id:
                  type: string
                timeCreated:
                  type: string
                  format: datetime
                resultType:
                  type: string
                yamls:
                  type: string
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: recommendednetworkpolicies
    singular: recommendednetworkpolicy
    kind: RecommendedNetworkPolicy
    shortNames:
      - rnp
