{{- if .Values.global.gitaly.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab.gitaly.serviceName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
  annotations:
  {{- if .Values.metrics.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.metrics.metricsPort }}"
  {{- end }}
    {{- include "gitlab.serviceAnnotations" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: "None"
  ports:
    - port: {{ .Values.service.externalPort }}
      name: {{ .Values.service.name }}
      targetPort: {{ .Values.service.internalPort }}
   {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.metricsPort }}
      name: {{ .Values.service.name }}-metrics
   {{- end }}
   {{- if $.Values.global.gitaly.tls.enabled }}
    - port: {{ .Values.service.tls.externalPort }}
      name: {{ .Values.service.name }}-tls
      targetPort: {{ .Values.service.tls.internalPort }}
   {{- end }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
{{- end }}
