apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alerting-executor
  name: alerting-executor
  namespace: "{{ .Values.namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-executor
  template:
    metadata:
      labels:
        app: alerting-executor
    spec:
      initContainers:
      - name: wait-mysql
        image: "{{ .Values.busyboxImage.repository }}:{{ .Values.busyboxImage.tag }}"
        imagePullPolicy: "{{ .Values.busyboxImage.pullPolicy }}"
        command: ['sh', '-c', 'until nc -z {{ .Values.dbHost }} {{ .Values.dbPort }}; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: "{{ .Values.busyboxImage.repository }}:{{ .Values.busyboxImage.tag }}"
        imagePullPolicy: "{{ .Values.busyboxImage.pullPolicy }}"
        command: ['sh', '-c', 'until nc -z {{ .Values.etcdHost }} {{ .Values.etcdPort }}; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - command:
        - /alerting/adapter
        image: "{{ .Values.adapterImage.repository }}:{{ .Values.adapterImage.tag }}"
        imagePullPolicy: "{{ .Values.adapterImage.pullPolicy }}"
        name: alerting-adapter
        env:
        - name: ADAPTER_APP_MONITORING_HOST
          value: "http://ks-apiserver.kubesphere-system.svc/kapis/monitoring.kubesphere.io/v1alpha2"
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "{{ .Values.resources.request.cpu }}"
            memory: "{{ .Values.resources.request.memory }}"
      - command:
        - /alerting/alert
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: alerting-executor
        env:
        - name: ALERT_APP_RUN_MODE
          value: "executor"
        - name: ALERT_MYSQL_HOST
          value: "{{ .Values.dbHost }}"
        - name: ALERT_ETCD_ENDPOINTS
          value: "{{ .Values.etcdEndpoint }}"
        - name: ALERT_APP_MONITORING_HOST
          value: "http://ks-apiserver.kubesphere-system.svc/kapis/monitoring.kubesphere.io/v1alpha2"
        - name: ALERT_QUEUE_TYPE
          value: "redis"
        - name: ALERT_QUEUE_ADDR
          value: "redis://{{ .Values.redisEndpoint }}"
        - name: ALERT_APP_NOTIFICATION_HOST
          value: "notification.kubesphere-alerting-system.svc:9201"
        - name: ALERT_LOG_LEVEL
          value: "info"
        - name: ALERT_MYSQL_LOG_MODE
          value: "false"
        resources:
          limits:
            cpu: "2"
            memory: 2000Mi
          requests:
            cpu: "{{ .Values.resources.request.cpu }}"
            memory: "{{ .Values.resources.request.memory }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alerting-watcher
  name: alerting-watcher
  namespace: kubesphere-alerting-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting-watcher
  template:
    metadata:
      labels:
        app: alerting-watcher
    spec:
      initContainers:
      - name: wait-mysql
        image: "{{ .Values.busyboxImage.repository }}:{{ .Values.busyboxImage.tag }}"
        imagePullPolicy: "{{ .Values.busyboxImage.pullPolicy }}"
        command: ['sh', '-c', 'until nc -z {{ .Values.dbHost }} {{ .Values.dbPort }}; do echo "waiting for mysql"; sleep 2; done;']
      - name: wait-etcd
        image: "{{ .Values.busyboxImage.repository }}:{{ .Values.busyboxImage.tag }}"
        imagePullPolicy: "{{ .Values.busyboxImage.pullPolicy }}"
        command: ['sh', '-c', 'until nc -z {{ .Values.etcdHost }} {{ .Values.etcdPort }}; do echo "waiting for etcd"; sleep 2; done;']
      containers:
      - command:
        - /alerting/alert
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.pullPolicy }}"
        name: alerting-watcher
        env:
        - name: ALERT_APP_RUN_MODE
          value: "watcher"
        - name: ALERT_MYSQL_HOST
          value: "{{ .Values.dbHost }}"
        - name: ALERT_ETCD_ENDPOINTS
          value: "{{ .Values.etcdEndpoint }}"
        - name: ALERT_QUEUE_TYPE
          value: "redis"
        - name: ALERT_QUEUE_ADDR
          value: "redis://{{ .Values.redisEndpoint }}"
        - name: ALERT_LOG_LEVEL
          value: "info"
        - name: ALERT_MYSQL_LOG_MODE
          value: "false"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: "{{ .Values.resources.request.cpu }}"
            memory: "{{ .Values.resources.request.memory }}"

