{{- if eq .Values.clickhouse.storage.createPersistentVolume.type "Local" }}
{{ $pvNum := int (mul .Values.clickhouse.cluster.shards .Values.clickhouse.cluster.replicas) }}
{{- range $i, $_ := until $pvNum }}
{{- if not (eq $i 0) }}
---
{{- end }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: clickhouse-pv-{{ $i }}
spec:
  storageClassName: clickhouse-storage
  capacity:
    storage: {{ $.Values.clickhouse.storage.size }}
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  local:
    path: {{ $.Values.clickhouse.storage.createPersistentVolume.local.path }}
  nodeAffinity:
  {{- if $.Values.clickhouse.storage.createPersistentVolume.local.affinity }}
  {{- with $.Values.clickhouse.storage.createPersistentVolume.local.affinity }}
    {{- toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- else }}
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: antrea.io/clickhouse-data-node
          operator: Exists
        {{- if gt (len $.Values.clickhouse.storage.createPersistentVolume.local.nodes) 0 }}
        - key: kubernetes.io/hostname
          operator: In
          values:
          - {{ index $.Values.clickhouse.storage.createPersistentVolume.local.nodes $i }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}
