apiVersion: v1
kind: Secret
metadata:
  name: clickhouse-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username: {{ .Values.clickhouse.connectionSecret.username }}
  password: {{ .Values.clickhouse.connectionSecret.password }}
