---
apiVersion: v1
data:
  ks-config.yaml: |
    ---
    persistence:
      storageClass: "{{ .Values.persistence.storageClass}}"
    etcd:
      monitoring: {{ .Values.etcd.monitoring }}
      endpointIps: {{ .Values.etcd.endpointIps }}
      port: {{ .Values.etcd.port }}
      tlsEnable: {{ .Values.etcd.tlsEnable }}
    common:
      mysqlVolumeSize: {{ .Values.common.mysqlVolumeSize }}
      minioVolumeSize: {{ .Values.common.minioVolumeSize }}
      etcdVolumeSize: {{ .Values.common.etcdVolumeSize }}
      openldapVolumeSize: {{ .Values.common.openldapVolumeSize }}
      redisVolumSize: {{ .Values.common.redisVolumSize }}
    metrics_server:
      enabled: {{ .Values.metrics_server.enabled }}
    console:
      enableMultiLogin: {{ .Values.console.enableMultiLogin }}
      port: {{ .Values.console.port }}
    monitoring:
      prometheusReplicas: {{ .Values.monitoring.prometheusReplicas }}
      prometheusMemoryRequest: {{ .Values.monitoring.prometheusMemoryRequest }}
      prometheusVolumeSize:  {{ .Values.monitoring.prometheusVolumeSize }}
      grafana:
        enabled: {{ .Values.monitoring.grafana.enabled }}
    logging:
      enabled: {{ .Values.logging.enabled }}
      elasticsearchMasterReplicas: {{ .Values.logging.elasticsearchMasterReplicas }}
      elasticsearchDataReplicas: {{ .Values.logging.elasticsearchDataReplicas }}
      logsidecarReplicas: {{ .Values.logging.logsidecarReplicas }}
      elasticsearchMasterVolumeSize: {{ .Values.logging.elasticsearchMasterVolumeSize }}
      elasticsearchDataVolumeSize: {{ .Values.logging.elasticsearchDataVolumeSize }}
      logMaxAge: {{ .Values.logging.logMaxAge }}
      elkPrefix: {{ .Values.logging.elkPrefix }}
      containersLogMountedPath: "{{ .Values.logging.containersLogMountedPath }}"
      kibana:
        enabled: {{ .Values.logging.kibana.enabled }}
    openpitrix:
      enabled: {{ .Values.openpitrix.enabled }}
    devops:
      enabled: {{ .Values.devops.enabled }}
      jenkinsMemoryLim: {{ .Values.devops.jenkinsMemoryLim }}
      jenkinsMemoryReq: {{ .Values.devops.jenkinsMemoryReq }}
      jenkinsVolumeSize: {{ .Values.devops.jenkinsVolumeSize }}
      jenkinsJavaOpts_Xms: {{ .Values.devops.jenkinsJavaOpts_Xms }}
      jenkinsJavaOpts_Xmx: {{ .Values.devops.jenkinsJavaOpts_Xmx }}
      jenkinsJavaOpts_MaxRAM: {{ .Values.devops.jenkinsJavaOpts_MaxRAM }}
      sonarqube:
        enabled: {{ .Values.devops.sonarqube.enabled }}
        postgresqlVolumeSize: {{ .Values.devops.sonarqube.postgresqlVolumeSize }}
    servicemesh:
      enabled: {{ .Values.servicemesh.enabled }}
    notification:
      enabled: {{ .Values.notification.enabled }}
    alerting:
      enabled: {{ .Values.alerting.enabled }}
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: kubesphere-system