{{- if .Values.global.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-grafana-import-secret
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
data:
  import-secret.sh: |-
{{ include (print $.Template.BasePath "/_import-secret.sh") . | indent 4 }}
{{- end }}
