{{- if .Values.global.grafana.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-grafana-import-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  import-secret.sh: |-
    {{- include (print $.Template.BasePath "/_import-secret.sh") . | nindent 4 }}
{{- end }}
