{{- if .Values.iomesh.create -}}
apiVersion: iomesh.com/v1alpha1
kind: IOMeshCluster
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
  labels:
  {{- include "iomesh.labels" . | nindent 4 }}
spec:
  version: {{ .Chart.Version }}
  {{- if .Values.iomesh.edition }}
  edition: {{ .Values.iomesh.edition }}
  {{- end }}
  {{- if .Values.iomesh.platform }}
  platform: {{ .Values.iomesh.platform }}
  {{- end }}
  {{- if .Values.iomesh.diskDeploymentMode }}
  diskDeploymentMode: {{ .Values.iomesh.diskDeploymentMode }}
  {{- end }}
  {{- with .Values.iomesh.cpuExclusiveOptions }}
  cpuExclusiveOptions:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storageClass: {{ .Values.iomesh.storageClass }}
  reclaimPolicy:
    volume: {{ .Values.iomesh.reclaimPolicy.volume }}
    blockdevice: {{ .Values.iomesh.reclaimPolicy.blockdevice }}
  meta:
    replicas: {{ .Values.iomesh.meta.replicaCount }}
    image:
      repository: {{ .Values.global.registry }}{{ .Values.iomesh.meta.image.repository }}
      tag: {{ .Values.iomesh.meta.image.tag | default (include "iomesh.version" .) }}
      pullPolicy: {{ .Values.iomesh.meta.image.pullPolicy }}
    {{- with .Values.iomesh.meta.podPolicy }}
    podPolicy:
      {{- with .nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- with .Values.iomesh.meta.resources }}
    resources:
      {{- toYaml . | nindent 6 }} 
    {{- end }}
  chunk:
    dataCIDR: {{ .Values.iomesh.chunk.dataCIDR }}
    {{- if .Values.iomesh.chunk.accessCIDR }}
    accessCIDR: {{ .Values.iomesh.chunk.accessCIDR }}
    {{- end }}
    replicas: {{ .Values.iomesh.chunk.replicaCount }}
    image:
      repository: {{ .Values.global.registry }}{{ .Values.iomesh.chunk.image.repository }}
      tag: {{ .Values.iomesh.chunk.image.tag | default (include "iomesh.version" .) }}
      pullPolicy: {{ .Values.iomesh.chunk.image.pullPolicy }}
    devicemanager:
      image:
        repository: {{ .Values.global.registry }}{{ .Values.iomesh.chunk.devicemanager.image.repository }}
        tag: {{ .Values.iomesh.chunk.devicemanager.image.tag | default (include "iomesh.operatorVersion" .)}}
        pullPolicy: {{ .Values.iomesh.chunk.devicemanager.image.pullPolicy }}
      {{- if .Values.iomesh.chunk.devicemanager.blockDeviceNamespace }}
      blockDeviceNamespace: {{ .Values.iomesh.chunk.devicemanager.blockDeviceNamespace }}
      {{- end }}
    {{- with .Values.iomesh.chunk.deviceMap }}
    deviceMap: 
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.iomesh.chunk.extraEnvs }}
    extraEnvs:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.iomesh.chunk.podPolicy }}
    podPolicy:
      {{- with .nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- if .Values.iomesh.chunk.resources }}
    resources:
      {{- toYaml .Values.iomesh.chunk.resources | nindent 6 }} 
    {{- end }}
  redirector:
    dataCIDR: {{ .Values.iomesh.chunk.dataCIDR }}
    {{- if .Values.iomesh.redirector.iscsiVirtualIP }}
    iscsiVirtualIP: {{ .Values.iomesh.redirector.iscsiVirtualIP }}
    {{- end }}
    image:
      repository: {{ .Values.global.registry }}{{ .Values.iomesh.redirector.image.repository }}
      tag: {{ .Values.iomesh.redirector.image.tag | default (include "iomesh.version" .) }}
      pullPolicy: {{ .Values.iomesh.redirector.image.pullPolicy }}
    {{- with .Values.iomesh.redirector.podPolicy }}
    podPolicy:
      {{- with .nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations: 
      {{- toYaml . | nindent 6 }}
      {{- end }}
    {{- end }}
    {{- with .Values.iomesh.redirector.resources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  probe:
    image:
      repository: {{ .Values.global.registry }}{{ .Values.iomesh.probe.image.repository }}
      tag: {{ .Values.iomesh.probe.image.tag | default (include "iomesh.operatorVersion" .) }}
      pullPolicy: {{ .Values.iomesh.probe.image.pullPolicy }}
  toolbox:
    image:
      repository: {{ .Values.global.registry }}{{ .Values.iomesh.toolbox.image.repository }}
      tag: {{ .Values.iomesh.toolbox.image.tag | default (include "iomesh.operatorVersion" .) }}
      pullPolicy: {{ .Values.iomesh.toolbox.image.pullPolicy }}
{{- end }}
