apiVersion: v1
kind: ServiceAccount
metadata:
  name: iomesh-post-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: iomesh-post-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  - pods
  verbs: ["*"]
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  verbs: ["*"]
- apiGroups:
  - batch
  resources:
  - jobs
  verbs: ["*"]
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs: ["*"]
- apiGroups:
  - iomesh.com
  - openebs.io
  - zookeeper.pravega.io
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: iomesh-post-delete-hook
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
subjects:
- kind: ServiceAccount
  name: iomesh-post-delete-hook
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: iomesh-post-delete-hook
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: iomesh-post-delete-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation, hook-failed
spec:
  serviceAccountName: iomesh-post-delete-hook
  restartPolicy: Never
  containers:
  - name: post-delete
    image: {{ .Values.global.registry }}iomesh/post-delete-hook:{{ .Values.operator.image.tag | default .Chart.Version }}
    imagePullPolicy: IfNotPresent
    env:
    - name: RELEASE_NAME
      value: {{ .Release.Name }}
    - name: RELEASE_NAMESPACE
      value: {{ .Release.Namespace }}
    volumeMounts:
    - mountPath: /sys/fs/cgroup
      name: cgroup
  volumes:
  - hostPath:
      path: /sys/fs/cgroup
      type: Directory
    name: cgroup
