apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "harbor.jobservice" . }}"
  labels:
{{ include "harbor.labels" . | indent 4 }}
type: Opaque
data:
  secret: {{ .Values.jobservice.secret | default (randAlphaNum 16) | b64enc | quote }}
