kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
    # containerPort below must match the values file:
    #   nginx-ingress.controller.service.nodePorts.https
  - containerPort: 32443
    hostPort: 443
    listenAddress: "0.0.0.0"
