global:
  hosts:
    domain: (your host IP).nip.io
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: false

# Don't use certmanager, we'll use http
certmanager:
  install: false

# Specify known ports and reduce replicas to 1
nginx-ingress:
  defaultBackend:
    replicaCount: 1
  controller:
    replicaCount: 1
    minAavailable: 1
    service:
      type: NodePort
      nodePorts:
        # http port value blow must match the KinD config file:
        #   nodes[0].extraPortMappings[0].containerPort
        http: 32080
        # ssh port value blow must match the KinD config file:
        #   nodes[0].extraPortMappings[1].containerPort
        ssh: 32022

# Allow privileged runners for Docker-in-Docker pipelines
gitlab-runner:
  runners:
    privileged: true
