apiVersion: v1
name: harbor
version: 1.4.1
appVersion: 2.0.1
description: An open source trusted cloud native registry that stores, signs, and scans content
keywords:
- docker
- registry
- harbor
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/harbor/master/docs/img/harbor_logo.png
sources:
- https://github.com/goharbor/harbor
- https://github.com/goharbor/harbor-helm
maintainers:
- name: Wenkai Yin
  email: yinw@vmware.com
- name: Weiwei He
  email: hweiwei@vmware.com
- name: Qian Deng
  email: dengq@vmware.com
engine: gotpl
annotations:
  "app.kubesphere.io/category": "Image Registry"
