{{- if .Values.Kubernetes -}}
{{- if .Values.output.forward.enable -}}
apiVersion: logging.kubesphere.io/v1alpha2
kind: Output
metadata:
  name: fluentd
  labels:
    logging.kubesphere.io/enabled: "true"
    logging.kubesphere.io/component: logging
spec:
  matchRegex: (?:kube|service)\.(.*)
  forward:
    host: {{ .Values.output.forward.host }}
    port: {{ .Values.output.forward.port }}
  {{- end }}
  {{- end }}