# Default values for OpenELB.
# This is a YAML-formatted file.

admission:
  image:
    repository: kubespheredev/kube-webhook-certgen
    tag: v1.1.1
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true
    name: openelb-admission

manager:
  apiHosts: ":50051"
  monitorEnable: false
  monitorPort: 50052
  webhookPort: 443
  image:
    repository: kubesphere/openelb
    tag: v0.5.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  terminationGracePeriodSeconds: 10
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
  nodeSelector:
    kubernetes.io/os: linux
    #lb.kubesphere.io/v1alpha1: openelb
  serviceAccount:
    create: true
    name: openelb-manager

customImage:
  enable: true
  vipImage: ""      # "kubesphere/kube-keepalived-vip:0.35"
  forwardImage: ""  # kubesphere/openelb-forward:master
  proxyImage: ""    # kubesphere/openelb-proxy:master
