apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5672
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: 15672
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
