{{- if .Values.grafana.enable }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.grafana.storage.persistentVolumeClaimSpec }}
  {{- with .Values.grafana.storage.persistentVolumeClaimSpec }}
  {{- toYaml . | trim | nindent 2 }}
  {{- end }}
  {{- else }}
  storageClassName: grafana-storage
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.storage.size }}
{{- end }}
