{{- if .Values.grafana.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ .Release.Namespace }}
  name: grafana-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: grafana-role
subjects:
  - kind: ServiceAccount
    name: grafana
    namespace: {{ .Release.Namespace }}
{{- end }}
