{{- if (eq (len .Values.clickhouse.cluster.zookeeperHosts) 0) }}
# Setup Headless Service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: zookeepers
  labels:
    app: zookeeper
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    what: node
{{- end }}
