{{- if (eq (len .Values.clickhouse.cluster.zookeeperHosts) 0) }}
# Setup max number of unavailable pods in StatefulSet
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pod-disruption-budget
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: zookeeper
  maxUnavailable: 1
{{- end }}
