apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "qiming-operator.fullname" . }}-role
rules:
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backupjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backupjobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - backups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - miganalytics
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - miganalytics/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - mighooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - mighooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migmigrations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - migstorages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restorejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restorejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.yinhestor.com
  resources:
  - restores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  - batch
  - extensions
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumes/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - servicemonitors
  verbs:
  - create
  - get
  - list
  - update
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - delete
  - watch
  - update
  - deletecollection
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "qiming-operator.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "qiming-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
