{{- if not .Values.s3Config.skipped }}
apiVersion: v1
data:
  aws-access-key-id: {{ .Values.s3Config.accessKey | required "access key id is required" | b64enc | quote }}
  aws-secret-access-key: {{ .Values.s3Config.secretKey | required "secret access key id is required" | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.s3Config.name | required "s3 name is required " }}
  namespace: {{ .Release.Namespace }}
type: Opaque
{{- end }}