{{- if .Values.velero.enabled }}
{{- if not .Values.s3Config.skipped }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qiming-operator.fullname" . }}-velero-installer
  labels:
    {{- include "qiming-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: velero-installer
      {{- include "qiming-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: velero-installer
        {{- include "qiming-operator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: velero-installer
        image: "{{ .Values.componentImages.veleroInstallerImage.repository }}:{{ .Values.componentImages.veleroInstallerImage.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ['sh', '-c', '/qiming/velero_installer.sh']
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VELERO_IMAGE
            value: {{ .Values.velero.image }}
          - name: VELERO_PLUGINS
            value: {{ .Values.velero.plugins }}
          - name: IMAGE_RESTIC_HELPER
            value: "{{ .Values.componentImages.resticHelperImage.repository }}:{{ .Values.componentImages.resticHelperImage.tag }}"
{{- if .Values.velero.disableSnapshot }}
          - name: VELERO_DISABLE_SNAPSHOT
            value: "true"
{{- end }}
          - name: S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3Config.name }}
                key: aws-access-key-id
          - name: S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.s3Config.name }}
                key: aws-secret-access-key
          - name: S3_CONFIG_S3URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3Config.name }}
                key: s3Url
          - name: S3_CONFIG_BUCKET
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3Config.name }}
                key: bucket
          - name: S3_CONFIG_REGION
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3Config.name }}
                key: region
          - name: S3_CONFIG_PROVIDER
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.s3Config.name }}
                key: provider
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "qiming-operator.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
{{- end }}
{{- end }}
      
