apiVersion: v1
kind: Service
metadata:
  name: {{ include "databend-meta.fullname" . }}
  labels:
    {{- include "databend-meta.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    {{- range $key, $val := .Values.service.ports }}
    - port: {{ $val }}
      targetPort: {{ $key}}
      protocol: TCP
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "databend-meta.selectorLabels" . | nindent 4 }}
