apiVersion: v2
name: stonedb-helm
description: A Helm chart for Kubernetes to run StoneDB standone

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.7_1.0.1"

home: "https://www.stoneatom.com/StoneDB"

sources:
  - "https://github.com/stoneatom/stonedb"
  - "https://github.com/stoneatom/stonedb-helm.git"

maintainers:
  - name: "stoneatom"
    email: "ops@stoneatom.com"

keywords:
  - "stonedb"
  - "stoneatom"
  - "database"
  - "mysql"
