{{- if or .Values.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "openelb.manager.serviceAccountName" . }}
  namespace: {{ template "openelb.namespace" . }}
  labels:
    {{- include "openelb.manager.labels" . | nindent 4 }}
{{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-keepalived-vip
  namespace: {{ template "openelb.namespace" . }}
  labels:
    {{- include "openelb.keepalived.labels" . | nindent 4 }}