apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openelb.manager.fullname" . }}
  namespace: {{ template "openelb.namespace" . }}
  labels:
    {{- include "openelb.manager.labels" . | nindent 4 }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "openelb.manager.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "openelb.manager.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "openelb.manager.serviceAccountName" . }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                {{- include "openelb.manager.labels" . | nindent 16 }}
            topologyKey: kubernetes.io/hostname
      nodeSelector:
      {{- toYaml .Values.manager.nodeSelector | nindent 8 }}
      containers:
      - command:
          - openelb-manager
        args:
          - --webhook-port={{ .Values.manager.webhookPort }}
          - --api-hosts={{ .Values.manager.apiHosts }}
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: OPENELB_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        image: {{ .Values.manager.image.repository }}:{{ .Values.manager.image.tag }}
        imagePullPolicy: {{ .Values.manager.image.pullPolicy }}
        name: openelb-manager
        ports:
          - containerPort: {{ .Values.manager.webhookPort }}
            name: webhook
            protocol: TCP
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - |
                gobgp -p 50051 global
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {{- toYaml .Values.manager.resources | nindent 10 }}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
            - NET_RAW
            - NET_BIND_SERVICE
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs/
            name: webhook-cert
            readOnly: true
      hostNetwork: true
      terminationGracePeriodSeconds: {{ .Values.manager.terminationGracePeriodSeconds }}
      tolerations: {{- toYaml .Values.manager.tolerations | nindent 8 }}
      volumes:
        - name: webhook-cert
          secret:
            items:
              - key: key
                path: tls.key
              - key: cert
                path: tls.crt
            secretName: {{ template "openelb.admission.fullname" . }}