{{ if .Values.manager.monitorEnable }}

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
  {{- include "openelb.manager.labels" . | nindent 4 }}
  name: {{ template "openelb.manager.fullname" . }}
  namespace: {{ template "openelb.namespace" . }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - {{ template "openelb.namespace" . }}
  selector:
    matchLabels:
      app: openelb-manager

{{ end }}