apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "update"]
