apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels" . | nindent 4 }}
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  {{- if .Values.license }}
  license: {{ .Values.license }}
  {{- end }}
type: Opaque
