# Default values for gitlab-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: registry.gitlab.com/gitlab-org/build/cng/gitlab-exporter
  pullSecrets: []
  # pullPolicy: IfNotPresent
  # tag: latest

service:
  name: gitlab-exporter
  type: ClusterIP
  externalPort: 9168
  internalPort: 9168

metrics:
  enabled: true
  port: 9168
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9168"
    prometheus.io/path: "/metrics"

enabled: true

# Tolerations for pod scheduling
tolerations: []

init:
  image: busybox
  tag: latest
  resources:
    requests:
      cpu: 50m

global:
  # imagePullPolicy: IfNotPresent
  redis:
    password: {}

redis:
  password: {}

resources:
  # limits:
  #  cpu: 1
  #  memory: 2G
  requests:
    cpu: 50m
    memory: 100M
