apiVersion: v1
appVersion: 1.3.4
description: Prometheus exporter for Redis metrics
home: https://github.com/oliver006/redis_exporter
keywords:
- prometheus
- redis
maintainers:
- email: arcadie.condrat@gmail.com
  name: acondrat
name: redis-exporter
sources:
- https://github.com/oliver006/redis_exporter
version: 3.4.6
annotations:
  "app.kubesphere.io/category": "Prometheus Exporter"
