apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litmus-portal.fullname" . }}-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "litmus-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-admin-secret
stringData:
  JWT_SECRET: "litmus-portal@123"
  DB_USER: "admin"
  DB_PASSWORD: "1234"