{{- if .Values.ingress.enabled -}}
{{ $fullName := include "litmus-portal.fullname" . }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  labels:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-frontend
    {{- include "litmus-portal.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- if .Values.ingress.host.name }}
  - host: {{ .Values.ingress.host.name | quote }}
    http:
  {{- else }}
  - http: 
  {{- end }}
      paths:
    {{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: {{ .Values.ingress.host.paths.frontend }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: litmusportal-frontend-service
            port:
              number: 9091
      - path: {{ .Values.ingress.host.paths.backend }}
        pathType: ImplementationSpecific
        backend:
          service: 
            name: litmusportal-server-service
            port: 
              number: 9002
    {{- else if semverCompare "<1.19-0" .Capabilities.KubeVersion.GitVersion }}
      - path: {{ .Values.ingress.host.paths.frontend }}
        backend:
          serviceName: litmusportal-frontend-service
          servicePort: 9091
      - path: {{ .Values.ingress.host.paths.backend }}
        backend: 
          serviceName: litmusportal-server-service
          servicePort: 9002
    {{- end }}
{{- end }}
