apiVersion: v1
kind: Service
metadata:
  name: {{ include "litmus-portal.fullname" . }}-mongo
  namespace:  {{ .Release.Namespace }}
  labels:
    app: mongo
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-database
    {{- include "litmus-portal.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongo.service.type }}
  ports:
    - name: mongodb
      port: {{ .Values.mongo.service.port }}
      targetPort: {{ .Values.mongo.service.targetPort }}
  selector:
    app.kubernetes.io/component: {{ include "litmus-portal.name" . }}-database
