{{- if and .Values.enabled (gt (.Values.controller.replicaCount | int) 1 ) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "nginx-ingress.controller.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "gitlab.standardLabels" . | indent 4 }}
    component: "{{ .Values.controller.name }}"
spec:
  selector:
    matchLabels:
      app: {{ template "nginx-ingress.name" . }}
      release: {{ .Release.Name }}
      component: "{{ .Values.controller.name }}"
  minAvailable: {{ .Values.controller.minAvailable }}
{{- end }}
