name: BuildHelmRepo

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'
      - 'release-*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: deploy index.yaml
        env:
          BASE_URL: https://charts.kubesphere.io
        run: ./build.sh deploy_charts

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit to gh-pages when merging to master
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          # Optional, but recommended
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change

          # Optional branch name where commit should be pushed to.
          # Defaults to the current branch.
          branch: gh-pages

          # Optional. Used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional commit user and author settings
          commit_user_name: KubeSphere CI Bot # defaults to "GitHub Actions"
          commit_user_email: ks-ci-bot@users.noreply.github.com # defaults to "actions@github.com"
          commit_author: Author KubeSphere CI Bot <ks-ci-bot@users.noreply.github.com> # defaults to author of the commit that triggered the run

          # Optional. Used by `git-status`
          # See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'

