{{- if .Values.prometheus.createNetworkPolicy -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Values.prometheus.namespace }}
  name: prometheus-{{ include "deck.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.prometheus.matchLabels | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name:  {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              {{- include "deck.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9090
{{- end }}
---
{{- if .Values.alertmanager.createNetworkPolicy -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .Values.alertmanager.namespace }}
  name: alertmanager-{{ include "deck.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.alertmanager.matchLabels | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name:  {{ .Release.Namespace }}
        - podSelector:
            matchLabels:
              {{- include "deck.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 9093
{{- end }}
