{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deck.serviceAccountName" . }}
  labels:
    {{- include "deck.labels" . | nindent 4 }}
{{- end }}
