{{- if .Values.theiaManager.enable }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: theia-manager
  name: theia-manager-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: theia-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: theia-manager-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
