{{- if .Values.theiaManager.enable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app: theia-manager
  name: theia-manager-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - theia-ca
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  # This is the content of built-in role kube-system/extension-apiserver-authentication-reader.
  # But it doesn't have list/watch permission before K8s v1.17.0 so the extension apiserver (antrea-agent) will
  # have permission issue after bumping up apiserver library to a version that supports dynamic authentication.
  # See https://github.com/kubernetes/kubernetes/pull/85375
  # To support K8s clusters older than v1.17.0, we grant the required permissions directly instead of relying on
  # the extension-apiserver-authentication role.
  - apiGroups: [""]
    resourceNames: ["extension-apiserver-authentication"]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["crd.theia.antrea.io"]
    resources: ["networkpolicyrecommendations", "recommendednetworkpolicies"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["crd.theia.antrea.io"]
    resources: ["networkpolicyrecommendations/status"]
    verbs: ["update"]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: ["list"]
  - apiGroups: [ "" ]
    resources: [ "services", "secrets" ]
    verbs: ["get"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications"]
    verbs: ["create", "delete", "get", "list"]
{{- end }}
